language: ruby
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - AWS_REGION=ap-southeast-1
    - PGPORT=5433
    - CC_TEST_REPORTER_ID=d99f01c52006e27c30fcd5f4f2840fa04597d4eca56cbbc36a9f795d8466ee3f
before_install:
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
before_script:
  - google-chrome-stable --headless --disable-gpu --no-sandbox
  - psql -c 'create database somleng_scfm_test;' -U travis
  - ./cc-test-reporter before-build
after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
