language: ruby
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
  code_climate:
    repo_token:
      secure: "PIV3i6vp+43fisDQoODIlWuH/rEDmTzMC4/85XLuCSagqfD34sLj6rNETfPl75dVwvsV/OQRmb5Lvy4ba4xFN0ga2GfWt3Pr3jnVmvnLr/HP80y4Z1X/4HeXRBK9NUUlu43iCXmPyXq+aPyW7TtXBTD0Olxz1ow/vwAlAIsJX3RNE1z8QUqDYdVyI9GRdQ5zLbQNUFvwtXgZCZW1GvJs5dDPJ3dpmAV8igzPW+rvakwQDOg11wS2dkK+4b17ktnfw9n5gviD6A79gveL8aM86a2kgLGaaYp/krvDpcqy2MykwjpgcH0jQtSfUV6VDj88DE0OTzpvJon2dFUnCbuIj8jgGBNxtcfHqgFC7FeO+9ZD2YJ5mEBb+mT1T/uwE9UxLz1JviGJg7iQ4L9HIGyQMzwHCOUBOJhVbBLm3SEyt8RKKUZUThOn8mFQI0cPcZaUeiZCOicdya0RCtQ/T8JlI3wlKXARcO2IBNr+ydvkw3zwkTrs6cP1j8A/OLrWznD160+cvGdghK71JdxTdgV5Tex0eubSmjhfDHs5Monj9mO/BudKxVNIt0Kn+JmAQDLV8XYt0INRcvzU/w7kRj1pzRGX5uvDsRX91B42SFAnMa9Gu61Qkc929Kw+qleN9R6+9kCEFUHtjcS45Wq1tiZst8T4+mm4YTUGEWVZ6TC4uVk="
env:
  global:
    - AWS_REGION=ap-southeast-1
    - PGPORT=5433
before_install:
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
before_script:
  - google-chrome-stable --headless --disable-gpu --no-sandbox
  - psql -c 'create database somleng_scfm_test;' -U travis
after_success:
  - bash -c 'if [[ "${START_SIMPLECOV}" = "1" ]]; then bundle exec codeclimate-test-reporter; fi'
