language: ruby
cache: bundler
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - AWS_REGION=ap-southeast-1
    - PGPORT=5433
    - secure: "HNt+tVkL42oJ+3CJFvMiDZAQI3D+bGqVf3xHBj24o/YOHlrqBZZwmyvGG1PPo/E27tjAji/lCOkTtzq/Y0UhyxqY1el9YclMC4/2Z1xbcKyDXgAI/6BFJDLvFT/s1JRocxjKXJSONBLlkqtDjOD4U1IRz8W+c5AyWtc9oufqCwOBympC8ZTUeI8pv2Y7KZ5MCxjaZfMCBbiGpAzRyDbavhah7oHQv/CbnXjByNdOnCneNtQbcnIbL9oWYdhPVavwG0fG6fWdisE1voo0SDQN1qqOpcDwkffbU02DnzmY8+gxyx96+yUJjKfuVIMwjYkj5C9+I3uYGeQ6XxF3brZTskrC1hobdiatx+CYLCa5nSFK+b7ZO6zXh81poGRBY/QpXZ9QFJO+h/WhbhDU+Z22pvlHKdcnshpqf617AJH3Z5aw5+xUjx6pBa2G90PtST1D4r4h2Da7w0Ow17mLViC/BOziU63GyJYfSg7ObEBr+TB0X/I7Q9jx0jJOamyHSg6GjAgyhRr8xONaOH9z3VDmOVoTulmQD345SiohIGbUpWrSXyEnY1ewE2HWzJMfe7HkR2ba4qNnJEh808PquXz38847Vi/Mt9WoPhHeIpViHNnC3yBuoholPoUmt8Q/djBo2brF/wEGdNeP4eUxMg6N3Gm2q1JIGBLum75Ke25+GQE="
before_install:
  - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
before_script:
  - google-chrome-stable --headless --disable-gpu --no-sandbox
  - psql -c 'create database somleng_scfm_test;' -U travis
deploy:
  - provider: elasticbeanstalk
    region: ap-southeast-1
    app: scfm
    env: scfm-webserver
    bucket_name: deploy.ews1294.info
    on:
      repo: PIN-Cambodia/somleng-scfm
      branch: master
  - provider: elasticbeanstalk
    region: ap-southeast-1
    app: scfm
    env: scfm-worker
    bucket_name: deploy.ews1294.info
    on:
      repo: PIN-Cambodia/somleng-scfm
      branch: master
