default: &default
  time_zone: "UTC"
  mailer_sender: "support@somleng.org"
  secret_key_base: "<%= Rails.application.credentials.secret_key_base %>"
  aws_sqs_default_queue_name: <%= ENV.fetch("AWS_SQS_DEFAULT_QUEUE_NAME", "default") %>
  aws_sqs_scheduler_queue_name: <%= ENV.fetch("AWS_SQS_SCHEDULER_QUEUE_NAME", "scheduler") %>
  aws_region: <%= ENV.fetch("AWS_DEFAULT_REGION", "ap-southeast-1") %>
  uploads_bucket: <%= ENV.fetch("UPLOADS_BUCKET", "uploads.somleng.org") %>
  audio_bucket: <%= ENV.fetch("AUDIO_BUCKET", "audio.somleng.org") %>

production: &production
  <<: *default
  default_url_host: "https://scfm.somleng.org"
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: "email-smtp.us-east-1.amazonaws.com"
  sentry_dsn: "<%= Rails.application.credentials.sentry_dsn %>"

development: &development
  <<: *production
  default_url_host: "http://localhost:3000"

test:
  <<: *development
  default_url_host: https://scfm.somleng.org
