default: &default
  time_zone: "UTC"
  mailer_sender: "support@somleng.org"
  secret_key_base: "<%= Rails.application.credentials.secret_key_base %>"

production: &production
  <<: *default
  default_queue_url: <%= ENV["DEFAULT_QUEUE_URL"] %>
  default_url_host: <%= ENV["DEFAULT_URL_HOST"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  aws_s3_access_key_id: <%= ENV["AWS_S3_ACCESS_KEY_ID"] %>
  aws_s3_secret_access_key: <%= ENV["AWS_S3_SECRET_ACCESS_KEY"] %>
  uploads_bucket: <%= ENV["UPLOADS_BUCKET"] %>
  audio_bucket: <%= ENV["AUDIO_BUCKET"] %>
  smtp_port: "587"
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_domain: "somleng.org"
  smtp_enable_starttls_auto: true
  smtp_authentication_method: "login"
  smtp_address: "email-smtp.us-east-1.amazonaws.com"
  sentry_dsn: "<%= Rails.application.credentials.sentry_dsn %>"

development: &development
  <<: *production
  default_queue_url: "https://example.com/path/to/queue_name"
  default_url_host: "localhost:3000"
  audio_bucket: "audio.somleng.org"
  smtp_address: "127.0.0.1"
  smtp_port: "1025"
  aws_region: "ap-southeast-1"

test:
  <<: *development
