default: &default
  time_zone: "UTC"
  mailer_sender: "support@somleng.org"
  secret_key_base: "<%= Rails.application.credentials.secret_key_base %>"
  aws_sqs_default_queue_name: <%= ENV.fetch("AWS_SQS_DEFAULT_QUEUE_NAME", "default") %>
  aws_sqs_scheduler_queue_name: <%= ENV.fetch("AWS_SQS_SCHEDULER_QUEUE_NAME", "scheduler") %>

production: &production
  <<: *default
  default_url_host: <%= ENV["DEFAULT_URL_HOST"] %>
  aws_region: <%= ENV["AWS_REGION"] %>
  uploads_bucket: <%= ENV["UPLOADS_BUCKET"] %>
  audio_bucket: <%= ENV["AUDIO_BUCKET"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: "email-smtp.us-east-1.amazonaws.com"
  sentry_dsn: "<%= Rails.application.credentials.sentry_dsn %>"

development: &development
  <<: *production
  default_url_host: "localhost:3000"
  audio_bucket: "audio.somleng.org"
  smtp_address: "127.0.0.1"
  smtp_port: "1025"
  aws_region: "ap-southeast-1"

test:
  <<: *development
