default: &default
  adapter: "postgresql"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  reaping_frequency: 10
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: "somleng_scfm_development"

test:
  <<: *default
  database: "somleng_scfm_test"

production:
  <<: *default
