delay: 15
queues:
  - <%= ENV.fetch("AWS_SQS_DEFAULT_QUEUE_NAME", "default") %>

groups:
  scheduler:
    concurrency: 5
    delay: 30
    queues:
      - <%= ENV.fetch("AWS_SQS_SCHEDULER_QUEUE_NAME", "scheduler") %>
